version: "3"

services:
  server:
    container_name: server
    build:
      context: .
    restart: always
    ports:
      - 6000:6000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - type: bind
        source: ../nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # Changed from 80:80 to 8080:80 to avoid conflict
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    external: true
