version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 6000:6000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    external: true
